//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArincApi.rc
//
#define ARAPI_PATCH_VER                 0
#define ARAPI_BUILD_VER                 0
#define ARINC_BOARD_TYPE_PCI            0
#define AR_WRAP_OFF                     0
#define AR_NONE                         0
#define AR_100K                         0
#define AR_HIGH                         0
#define ARS_SDI_00                      0
#define ARU_FILTER_OFF                  0
#define ARS_NODATA                      0
#define AR_WORD_LABEL_OFFSET            0
#define ARAPI_MINOR_VER                 1
#define ARINC_BOARD_TYPE_USB            1
#define ARU_XMIT_RATE                   1
#define AR_WRAP_ON                      1
#define AR_ODD                          1
#define AR_50K                          1
#define ARS_SDI_01                      1
#define ARU_FILTER_ON                   1
#define ARS_NORMAL                      1
#define AR_WORD_SDI_0                   0x01
#define ARAPI_MAJOR_VER                 2
#define ARINC_BOARD_TYPE_UNKNOWN        2
#define ARU_RECV_RATE                   2
#define AR_EVEN                         2
#define ARS_SDI_10                      2
#define AR_WORD_SDI_1                   0x02
#define ARU_PARITY                      3
#define AR_12_5K                        3
#define AR_12K5                         3
#define AR_LOW                          3
#define ARS_SDI_11                      3
#define ARU_INTERNAL_WRAP               4
#define ARS_GOTDATA                     4
#define AR_ON                           7
#define AR_OFF                          8
#define AR_WORD_SDI_OFFSET              8
#define AR_WORD_DATA_OFFSET             10
#define ARINC_MAX_CH_NUM                16
#define AR_WORD_SSM_OFFSET              29
#define AR_WORD_PARITY_OFFSET           31
#define AR_WORD_WIDTH                   32
#define AR_WORD_LABEL_MASK              0x000000FF
#define ARINC_LABEL_NUM                 256
#define AR_LABEL_NUM                    256
#define ARU_CH01_LOOPBACK               300
#define ARU_CH02_LOOPBACK               301
#define ARU_CH03_LOOPBACK               302
#define ARU_CH04_LOOPBACK               303
#define ARU_CH05_LOOPBACK               304
#define ARU_CH06_LOOPBACK               305
#define ARU_CH07_LOOPBACK               306
#define ARU_CH08_LOOPBACK               307
#define ARU_CH09_LOOPBACK               308
#define ARU_CH10_LOOPBACK               309
#define ARU_CH11_LOOPBACK               310
#define ARU_CH12_LOOPBACK               311
#define ARU_CH13_LOOPBACK               312
#define ARU_CH14_LOOPBACK               313
#define ARU_CH15_LOOPBACK               314
#define ARU_CH16_LOOPBACK               315
#define ARU_RX_CH01_BIT_RATE            500
#define ARU_RX_CH02_BIT_RATE            501
#define ARU_RX_CH03_BIT_RATE            502
#define ARU_RX_CH04_BIT_RATE            503
#define ARU_RX_CH05_BIT_RATE            504
#define ARU_RX_CH06_BIT_RATE            505
#define ARU_RX_CH07_BIT_RATE            506
#define ARU_RX_CH08_BIT_RATE            507
#define ARU_RX_CH09_BIT_RATE            508
#define ARU_RX_CH10_BIT_RATE            509
#define ARU_RX_CH11_BIT_RATE            510
#define ARU_RX_CH12_BIT_RATE            511
#define ARU_ALL_LABELS                  0x1FF
#define ARU_RX_CH13_BIT_RATE            512
#define ARU_RX_CH14_BIT_RATE            513
#define ARU_RX_CH15_BIT_RATE            514
#define ARU_RX_CH16_BIT_RATE            515
#define ARU_TX_CH01_BIT_RATE            700
#define ARU_TX_CH02_BIT_RATE            701
#define ARU_TX_CH03_BIT_RATE            702
#define ARU_TX_CH04_BIT_RATE            703
#define ARU_TX_CH05_BIT_RATE            704
#define ARU_TX_CH06_BIT_RATE            705
#define ARU_TX_CH07_BIT_RATE            706
#define ARU_TX_CH08_BIT_RATE            707
#define ARU_TX_CH09_BIT_RATE            708
#define ARU_TX_CH10_BIT_RATE            709
#define ARU_TX_CH11_BIT_RATE            710
#define ARU_TX_CH12_BIT_RATE            711
#define ARU_TX_CH13_BIT_RATE            712
#define ARU_TX_CH14_BIT_RATE            713
#define ARU_TX_CH15_BIT_RATE            714
#define ARU_TX_CH16_BIT_RATE            715
#define AR_WORD_SDI_MASK                0x00000300
#define ARU_RX_CH01_PARITY              900
#define ARU_RX_CH02_PARITY              901
#define ARU_RX_CH03_PARITY              902
#define ARU_RX_CH04_PARITY              903
#define ARU_RX_CH05_PARITY              904
#define ARU_RX_CH06_PARITY              905
#define ARU_RX_CH07_PARITY              906
#define ARU_RX_CH08_PARITY              907
#define ARU_RX_CH09_PARITY              908
#define ARU_RX_CH10_PARITY              909
#define ARU_RX_CH11_PARITY              910
#define ARU_RX_CH12_PARITY              911
#define ARU_RX_CH13_PARITY              912
#define ARU_RX_CH14_PARITY              913
#define ARU_RX_CH15_PARITY              914
#define ARU_RX_CH16_PARITY              915
#define ARS_TIMEOUT                     1003
#define ARS_INVHARCMD                   1004
#define ARS_INVHARVAL                   1005
#define ARS_XMITOVRFLO                  1006
#define ARS_INVBOARD                    1007
#define ARS_BRDNOTLOAD                  1008
#define ARS_INVARG                      1009
#define ARS_WINRTFAIL                   1010
#define ARU_TX_CH01_PARITY              1100
#define ARU_TX_CH02_PARITY              1101
#define ARU_TX_CH03_PARITY              1102
#define ARU_TX_CH04_PARITY              1103
#define ARU_TX_CH05_PARITY              1104
#define ARU_TX_CH06_PARITY              1105
#define ARU_TX_CH07_PARITY              1106
#define ARU_TX_CH08_PARITY              1107
#define ARU_TX_CH09_PARITY              1108
#define ARU_TX_CH10_PARITY              1109
#define ARU_TX_CH11_PARITY              1110
#define ARU_TX_CH12_PARITY              1111
#define ARU_TX_CH13_PARITY              1112
#define ARU_TX_CH14_PARITY              1113
#define ARU_TX_CH15_PARITY              1114
#define ARU_TX_CH16_PARITY              1115
#define ARU_CH01_DECODER                1300
#define ARU_CH02_DECODER                1301
#define ARU_CH03_DECODER                1302
#define ARU_CH04_DECODER                1303
#define ARU_CH05_DECODER                1304
#define ARU_CH06_DECODER                1305
#define ARU_CH07_DECODER                1306
#define ARU_CH08_DECODER                1307
#define ARU_CH09_DECODER                1308
#define ARU_CH10_DECODER                1309
#define ARU_CH11_DECODER                1310
#define ARU_CH12_DECODER                1311
#define ARU_CH13_DECODER                1312
#define ARU_CH14_DECODER                1313
#define ARU_CH15_DECODER                1314
#define ARU_CH16_DECODER                1315
#define ARU_CH01_SDI                    1400
#define ARU_CH02_SDI                    1401
#define ARU_CH03_SDI                    1402
#define ARU_CH04_SDI                    1403
#define ARU_CH05_SDI                    1404
#define ARU_CH06_SDI                    1405
#define ARU_CH07_SDI                    1406
#define ARU_CH08_SDI                    1407
#define ARU_CH09_SDI                    1408
#define ARU_CH10_SDI                    1409
#define ARU_CH11_SDI                    1410
#define ARU_CH12_SDI                    1411
#define ARU_CH13_SDI                    1412
#define ARU_CH14_SDI                    1413
#define ARU_CH15_SDI                    1414
#define ARU_CH16_SDI                    1415
#define ARS_FAILURE                     -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
