
#ifndef _ARAPI_VERSION_H_
#define _ARAPI_VERSION_H_

#include "arapi.h"

#define HR_MK_VER_STR(MAJOR, MINOR, PATCH, BUILD) #MAJOR"."#MINOR"."#PATCH"."#BUILD

#define HR_VER_FILE            ARAPI_MAJOR_VER, ARAPI_MINOR_VER, ARAPI_PATCH_VER, ARAPI_BUILD_VER
#define HR_VER_PRODUCT         ARAPI_MAJOR_VER, ARAPI_MINOR_VER, ARAPI_PATCH_VER, ARAPI_BUILD_VER
#define HR_VER_STRING_FILE     HR_MK_VER_STR(ARAPI_MAJOR_VER, ARAPI_MINOR_VER, ARAPI_PATCH_VER, ARAPI_BUILD_VER)
#define HR_VER_STRING_PRODUCT  HR_MK_VER_STR(ARAPI_MAJOR_VER, ARAPI_MINOR_VER, ARAPI_PATCH_VER, ARAPI_BUILD_VER)

#endif  // _ARAPI_VERSION_H_
