
#ifndef _PCI429_ADD_DEVICE_H_
#define _PCI429_ADD_DEVICE_H_

EVT_WDF_DRIVER_DEVICE_ADD       EvtDriverDeviceAdd;
EVT_WDF_DEVICE_CONTEXT_CLEANUP  EvtDeviceContextCleanup;

#endif	// _PCI429_ADD_DEVICE_H_
