
#ifndef _PCI429_DRIVER_PUBLIC_H_
#define _PCI429_DRIVER_PUBLIC_H_

#include <InitGuid.h>

// {9E208E47-B593-4DE2-81D0-4AC96098328A}
DEFINE_GUID(GUID_DEVCLASS_PCI429,
	0x9e208e47, 0xb593, 0x4de2, 0x81, 0xd0, 0x4a, 0xc9, 0x60, 0x98, 0x32, 0x8a);

//! IOCTL definitions

// 设置用户事件
#define IOCTL_PCI429_SET_EVENT         CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 0x801, METHOD_BUFFERED, FILE_WRITE_ACCESS)

// 使能/禁止中断
#define IOCTL_PCI429_SET_INTERRUPT     CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)

// 读寄存器
#define IOCTL_PCI429_READ_REGISTER     CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS)

// 写寄存器
#define IOCTL_PCI429_WRITE_REGISTER    CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 0x804, METHOD_BUFFERED, FILE_WRITE_ACCESS)

// 启用/禁用LABEL0
#define IOCTL_PCI429_SET_LABEL0        CTL_CODE(FILE_DEVICE_BUS_EXTENDER, 0x805, METHOD_BUFFERED, FILE_WRITE_ACCESS)

// the atom of tx
typedef struct _ATOM_TDATA_INFO
{
	ULONG channel;
	ULONG BufferSize;
	ULONG *Buffer;

} ATOM_TDATA_INFO, *PATOM_TDATA_INFO;

// the atom of circular buffer
typedef struct _ATOM_RDATA_INFO
{
	ULONG data;
	LONGLONG timestamp;
	ULONG channel;

} ATOM_RDATA_INFO, *PATOM_RDATA_INFO;

#endif	// _PCI429_DRIVER_PUBLIC_H_
