
#ifndef TARGET_VERSION_H
#define TARGET_VERSION_H

// ²úÆ·°æ±¾
#define ARINCTOOL_MAJOR_VER  2
#define ARINCTOOL_MINOR_VER  3
#define ARINCTOOL_PATCH_VER  0
#define ARINCTOOL_BUILD_VER  0

#define HR_MK_VER_STR(MAJOR, MINOR, PATCH, BUILD) #MAJOR"."#MINOR"."#PATCH"."#BUILD

#define HR_VER_FILE            ARINCTOOL_MAJOR_VER, ARINCTOOL_MINOR_VER, ARINCTOOL_PATCH_VER, ARINCTOOL_BUILD_VER
#define HR_VER_PRODUCT         ARINCTOOL_MAJOR_VER, ARINCTOOL_MINOR_VER, ARINCTOOL_PATCH_VER, ARINCTOOL_BUILD_VER
#define HR_VER_STRING_FILE     HR_MK_VER_STR(ARINCTOOL_MAJOR_VER, ARINCTOOL_MINOR_VER, ARINCTOOL_PATCH_VER, ARINCTOOL_BUILD_VER)
#define HR_VER_STRING_PRODUCT  HR_MK_VER_STR(ARINCTOOL_MAJOR_VER, ARINCTOOL_MINOR_VER, ARINCTOOL_PATCH_VER, ARINCTOOL_BUILD_VER)

#endif	// TARGET_VERSION_H
